version: '2'
services:
  pptpd:
    image: "hotsun/pptpd-server"
    container_name: "pptpd-server"
    restart: "on-failure:10"
    network_mode: "bridge"
    ports:
      - "1723:1723"
    volumes: 
      - "./chap-secrets:/etc/ppp/chap-secrets"
